# -*- coding: utf-8 -*-
"""forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CT2GiL2AZglv851jpzd9V7bgX9-3D3O3
"""

# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from prophet import Prophet
from sklearn.metrics import mean_absolute_error, mean_squared_error
import warnings
warnings.filterwarnings('ignore')
from scipy import stats
import json
from datetime import datetime, timedelta
import random

# Set random seeds for reproducibility
np.random.seed(42)
random.seed(42)

#step1

def generate_better_synthetic_dataset():
    """
    Generate a MORE REALISTIC synthetic time series dataset with:
    - Daily data for 2+ years (800+ days)
    - Clear seasonal patterns (yearly, weekly)
    - External regressors with proper relationships
    - Reasonable noise levels
    """
    print("Generating improved synthetic dataset...")

    # Create date range: 800 days starting from 2022-01-01
    dates = pd.date_range(start='2022-01-01', periods=800, freq='D')

    # 1. Linear trend with one changepoint
    trend = np.linspace(100, 200, len(dates))
    # Add a changepoint at day 400
    trend[400:] += np.linspace(0, 30, 400)

    # 2. Clear yearly seasonality (365.25 days for leap years)
    day_of_year = dates.dayofyear + (dates.hour / 24)
    yearly_season = 25 * np.sin(2 * np.pi * day_of_year / 365.25)

    # 3. Weekly seasonality
    day_of_week = dates.dayofweek + (dates.hour / 24)
    weekly_season = 15 * np.sin(2 * np.pi * day_of_week / 7)

    # 4. Generate external regressors with proper relationships
    # Temperature (correlated with yearly seasonality)
    temperature = 15 + 12 * np.sin(2 * np.pi * day_of_year / 365.25) + np.random.normal(0, 5, len(dates))

    # Economic indicator (slow trend with some correlation to target)
    economic = 100 + np.cumsum(np.random.normal(0.05, 0.3, len(dates)))

    # 5. Holiday effects (more realistic)
    holiday_effect = np.zeros(len(dates))
    # December holidays
    dec_mask = (dates.month == 12) & (dates.day >= 20) & (dates.day <= 27)
    holiday_effect[dec_mask] = np.random.normal(25, 5, dec_mask.sum())
    # July holidays
    jul_mask = (dates.month == 7) & (dates.day >= 1) & (dates.day <= 7)
    holiday_effect[jul_mask] = np.random.normal(20, 4, jul_mask.sum())

    # 6. Add a few outliers (but not too many)
    outliers = np.zeros(len(dates))
    outlier_indices = random.sample(range(100, 700), 8)  # Fewer outliers
    for idx in outlier_indices:
        outliers[idx] = np.random.normal(40, 15)  # Smaller outliers

    # 7. Combine with realistic weights
    y = (
        trend * 1.0 +
        yearly_season * 1.0 +
        weekly_season * 0.7 +
        temperature * 0.4 +      # Temperature has moderate effect
        economic * 0.3 +         # Economic indicator has smaller effect
        holiday_effect * 1.0 +
        outliers +
        np.random.normal(0, 8, len(dates))  # Moderate noise
    )

    # Create DataFrame
    df = pd.DataFrame({
        'ds': dates,
        'y': y,
        'temperature': temperature,
        'economic': economic,
        'holiday_effect': holiday_effect,
        'is_holiday': ((holiday_effect > 10) | dec_mask | jul_mask).astype(int)
    })

    print(f"Dataset generated: {len(df)} days")
    print(f"Date range: {df['ds'].min()} to {df['ds'].max()}")
    return df

# Generate the improved dataset
synthetic_df = generate_better_synthetic_dataset()

#step 2

def explore_dataset(df):
    """Explore and visualize the dataset."""

    print("\n" + "="*60)
    print("DATASET EXPLORATION")
    print("="*60)

    # Basic statistics
    print("\n1. BASIC STATISTICS:")
    print(f"   - Mean target value: {df['y'].mean():.2f}")
    print(f"   - Std target value: {df['y'].std():.2f}")
    print(f"   - Min target value: {df['y'].min():.2f}")
    print(f"   - Max target value: {df['y'].max():.2f}")

    # Correlation analysis
    print("\n2. CORRELATION ANALYSIS:")
    correlation_matrix = df[['y', 'temperature', 'economic', 'holiday_effect']].corr()
    print("\nCorrelation Matrix:")
    print(correlation_matrix.round(3))

    # Visualize
    fig, axes = plt.subplots(2, 2, figsize=(15, 10))

    # Full time series
    axes[0, 0].plot(df['ds'], df['y'], 'b-', alpha=0.7, linewidth=1)
    axes[0, 0].set_title('Full Time Series (Target Variable)')
    axes[0, 0].set_xlabel('Date')
    axes[0, 0].set_ylabel('Value')
    axes[0, 0].grid(True, alpha=0.3)

    # Last 90 days zoom
    axes[0, 1].plot(df['ds'][-90:], df['y'][-90:], 'b-', alpha=0.7, linewidth=1.5)
    axes[0, 1].set_title('Recent 90 Days (Detailed View)')
    axes[0, 1].set_xlabel('Date')
    axes[0, 1].set_ylabel('Value')
    axes[0, 1].grid(True, alpha=0.3)

    # External regressors
    axes[1, 0].plot(df['ds'], df['temperature'], 'orange', alpha=0.7, label='Temperature')
    axes[1, 0].plot(df['ds'], df['economic'], 'green', alpha=0.7, label='Economic')
    axes[1, 0].set_title('External Regressors')
    axes[1, 0].set_xlabel('Date')
    axes[1, 0].set_ylabel('Value')
    axes[1, 0].legend()
    axes[1, 0].grid(True, alpha=0.3)

    # Holiday effects
    holiday_mask = df['is_holiday'] == 1
    axes[1, 1].scatter(df['ds'][holiday_mask], df['y'][holiday_mask],
                       color='red', s=30, alpha=0.7, label='Holidays', zorder=5)
    axes[1, 1].plot(df['ds'], df['y'], 'b-', alpha=0.3, linewidth=0.5, label='Full Series')
    axes[1, 1].set_title('Holiday Effects on Target')
    axes[1, 1].set_xlabel('Date')
    axes[1, 1].set_ylabel('Value')
    axes[1, 1].legend()
    axes[1, 1].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig('dataset_exploration.png', dpi=150, bbox_inches='tight')
    plt.show()

explore_dataset(synthetic_df)

#stem 3

def prepare_prophet_data(df, train_test_split=0.8):
    """Prepare data for Prophet modeling."""

    # Prophet requires columns 'ds' and 'y'
    prophet_df = df[['ds', 'y']].copy()
    prophet_df['temperature'] = df['temperature']
    prophet_df['economic'] = df['economic']

    # Split into train and test
    split_idx = int(len(prophet_df) * train_test_split)
    train_df = prophet_df.iloc[:split_idx].copy()
    test_df = prophet_df.iloc[split_idx:].copy()

    # Create holiday dataframe
    holiday_df = df[df['is_holiday'] == 1][['ds']].copy()
    holiday_df['holiday'] = 'synthetic_holiday'

    print(f"\nData Preparation:")
    print(f"  Train set: {len(train_df)} days ({train_df['ds'].min().date()} to {train_df['ds'].max().date()})")
    print(f"  Test set:  {len(test_df)} days ({test_df['ds'].min().date()} to {test_df['ds'].max().date()})")
    print(f"  Holidays:  {len(holiday_df)} days identified")

    return train_df, test_df, holiday_df

train_df, test_df, holiday_df = prepare_prophet_data(synthetic_df)

#step 4

def rolling_origin_cv(train_df, holiday_df, initial_days=365, horizon=30, step=30):
    """Perform rolling origin cross-validation for time series."""

    print("\n" + "="*60)
    print("ROLLING ORIGIN CROSS-VALIDATION")
    print("="*60)

    cv_results = []
    total_points = len(train_df)
    fold_num = 1
    start_idx = initial_days

    while start_idx + horizon <= total_points:
        # Split train and validation
        train_cv = train_df.iloc[:start_idx].copy()
        val_cv = train_df.iloc[start_idx:start_idx + horizon].copy()

        # Initialize Prophet model
        model_cv = Prophet(
            yearly_seasonality=True,
            weekly_seasonality=True,
            daily_seasonality=False,  # Daily too noisy for daily data
            holidays=holiday_df,
            changepoint_prior_scale=0.05,
            seasonality_prior_scale=10,
            holidays_prior_scale=10,
            seasonality_mode='additive',
            interval_width=0.80  # For 80% intervals
        )

        # Add external regressors
        model_cv.add_regressor('temperature')
        model_cv.add_regressor('economic')

        # Fit model
        model_cv.fit(train_cv)

        # Create future dataframe
        future_cv = model_cv.make_future_dataframe(periods=horizon)
        future_cv = future_cv.merge(
            train_df[['ds', 'temperature', 'economic']],
            on='ds',
            how='left'
        )

        # Forecast
        forecast_cv = model_cv.predict(future_cv)

        # Extract validation predictions
        val_pred = forecast_cv.iloc[-horizon:][['ds', 'yhat', 'yhat_lower', 'yhat_upper']]
        val_actual = val_cv[['ds', 'y']]

        # Merge and calculate metrics
        val_results = pd.merge(val_pred, val_actual, on='ds')
        mae = mean_absolute_error(val_results['y'], val_results['yhat'])
        rmse = np.sqrt(mean_squared_error(val_results['y'], val_results['yhat']))

        # Calculate coverage for 80% interval
        coverage_80 = np.mean(
            (val_results['y'] >= val_results['yhat_lower']) &
            (val_results['y'] <= val_results['yhat_upper'])
        )

        cv_results.append({
            'fold': fold_num,
            'train_start': train_cv['ds'].min().date(),
            'train_end': train_cv['ds'].max().date(),
            'val_start': val_cv['ds'].min().date(),
            'val_end': val_cv['ds'].max().date(),
            'mae': mae,
            'rmse': rmse,
            'coverage_80': coverage_80
        })

        print(f"Fold {fold_num}: Train: {train_cv['ds'].min().date()} to {train_cv['ds'].max().date()}, "
              f"Val: {val_cv['ds'].min().date()} to {val_cv['ds'].max().date()}, "
              f"MAE: {mae:.2f}, Coverage: {coverage_80*100:.1f}%")

        fold_num += 1
        start_idx += step

    cv_results_df = pd.DataFrame(cv_results)

    print(f"\nCross-validation Summary:")
    print(f"  Folds completed: {len(cv_results)}")
    print(f"  Average MAE: {cv_results_df['mae'].mean():.2f}")
    print(f"  Average RMSE: {cv_results_df['rmse'].mean():.2f}")
    print(f"  Average 80% Coverage: {cv_results_df['coverage_80'].mean()*100:.1f}%")

    return cv_results_df

# Run cross-validation
cv_results = rolling_origin_cv(train_df, holiday_df, initial_days=365, horizon=60, step=30)

#step 5

def tune_hyperparameters(train_df, holiday_df, n_iterations=10):
    """Tune Prophet hyperparameters using simple random search."""

    print("\n" + "="*60)
    print("HYPERPARAMETER TUNING")
    print("="*60)

    # Parameter grid
    param_grid = {
        'changepoint_prior_scale': [0.01, 0.05, 0.1, 0.5],
        'seasonality_prior_scale': [5, 10, 20],
        'holidays_prior_scale': [5, 10, 20],
        'seasonality_mode': ['additive']
    }

    # Split for validation
    tune_train = train_df.iloc[:int(len(train_df) * 0.7)]
    tune_val = train_df.iloc[int(len(train_df) * 0.7):]

    best_score = float('inf')
    best_params = None
    results = []

    for i in range(n_iterations):
        # Sample parameters
        params = {
            'changepoint_prior_scale': np.random.choice(param_grid['changepoint_prior_scale']),
            'seasonality_prior_scale': np.random.choice(param_grid['seasonality_prior_scale']),
            'holidays_prior_scale': np.random.choice(param_grid['holidays_prior_scale']),
            'seasonality_mode': np.random.choice(param_grid['seasonality_mode'])
        }

        try:
            # Initialize model
            model_tune = Prophet(
                yearly_seasonality=True,
                weekly_seasonality=True,
                daily_seasonality=False,
                holidays=holiday_df,
                changepoint_prior_scale=params['changepoint_prior_scale'],
                seasonality_prior_scale=params['seasonality_prior_scale'],
                holidays_prior_scale=params['holidays_prior_scale'],
                seasonality_mode=params['seasonality_mode'],
                interval_width=0.80
            )

            model_tune.add_regressor('temperature')
            model_tune.add_regressor('economic')

            # Fit and predict
            model_tune.fit(tune_train)
            future_tune = model_tune.make_future_dataframe(periods=len(tune_val))
            future_tune = future_tune.merge(
                train_df[['ds', 'temperature', 'economic']],
                on='ds',
                how='left'
            )
            forecast_tune = model_tune.predict(future_tune)

            # Calculate metrics
            val_pred = forecast_tune.iloc[-len(tune_val):]['yhat'].values
            val_actual = tune_val['y'].values
            rmse = np.sqrt(mean_squared_error(val_actual, val_pred))

            # Store results
            results.append({
                'iteration': i + 1,
                'params': params,
                'rmse': rmse
            })

            print(f"Iteration {i+1}: RMSE = {rmse:.2f}")

            # Update best
            if rmse < best_score:
                best_score = rmse
                best_params = params

        except Exception as e:
            print(f"Iteration {i+1} failed: {str(e)[:50]}...")
            continue

    # If tuning failed, use reasonable defaults
    if best_params is None:
        best_params = {
            'changepoint_prior_scale': 0.05,
            'seasonality_prior_scale': 10,
            'holidays_prior_scale': 10,
            'seasonality_mode': 'additive'
        }
        print("Using default parameters")
    else:
        print(f"\nBest RMSE: {best_score:.2f}")
        print(f"Best parameters: {best_params}")

    return best_params

best_params = tune_hyperparameters(train_df, holiday_df, n_iterations=8)

#step 6

def train_final_model(train_df, test_df, holiday_df, best_params):
    """Train final Prophet model with tuned parameters."""

    print("\n" + "="*60)
    print("TRAINING FINAL MODEL")
    print("="*60)

    # Train TWO models: one for 80% intervals, one for 95% intervals
    print("Training model for 80% prediction intervals...")
    model_80 = Prophet(
        yearly_seasonality=True,
        weekly_seasonality=True,
        daily_seasonality=False,
        holidays=holiday_df,
        changepoint_prior_scale=best_params['changepoint_prior_scale'],
        seasonality_prior_scale=best_params['seasonality_prior_scale'],
        holidays_prior_scale=best_params['holidays_prior_scale'],
        seasonality_mode=best_params['seasonality_mode'],
        interval_width=0.80,  # 80% intervals
        uncertainty_samples=1000
    )

    print("Training model for 95% prediction intervals...")
    model_95 = Prophet(
        yearly_seasonality=True,
        weekly_seasonality=True,
        daily_seasonality=False,
        holidays=holiday_df,
        changepoint_prior_scale=best_params['changepoint_prior_scale'],
        seasonality_prior_scale=best_params['seasonality_prior_scale'],
        holidays_prior_scale=best_params['holidays_prior_scale'],
        seasonality_mode=best_params['seasonality_mode'],
        interval_width=0.95,  # 95% intervals
        uncertainty_samples=1000
    )

    # Add regressors to both models
    for model in [model_80, model_95]:
        model.add_regressor('temperature')
        model.add_regressor('economic')

    # Fit both models
    model_80.fit(train_df)
    model_95.fit(train_df)

    # Create future dataframes
    future = model_80.make_future_dataframe(periods=len(test_df))
    future = future.merge(
        test_df[['ds', 'temperature', 'economic']],
        on='ds',
        how='left'
    )

    # Fill missing values
    for col in ['temperature', 'economic']:
        future[col] = future[col].fillna(future[col].mean())

    # Generate forecasts
    print("Generating forecasts...")
    forecast_80 = model_80.predict(future)
    forecast_95 = model_95.predict(future)

    # Combine forecasts
    forecast = forecast_80[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].copy()
    forecast.rename(columns={
        'yhat_lower': 'yhat_lower_80',
        'yhat_upper': 'yhat_upper_80'
    }, inplace=True)

    # Add 95% intervals
    forecast['yhat_lower_95'] = forecast_95['yhat_lower']
    forecast['yhat_upper_95'] = forecast_95['yhat_upper']

    # Add actual values
    all_actual = pd.concat([train_df[['ds', 'y']], test_df[['ds', 'y']]])
    forecast = forecast.merge(all_actual, on='ds', how='left')

    print("Model training complete!")

    return model_80, model_95, forecast

model_80, model_95, forecast = train_final_model(train_df, test_df, holiday_df, best_params)

#step 7

def evaluate_model_performance(forecast, test_df):
    """Evaluate model performance and calibration."""

    print("\n" + "="*60)
    print("MODEL EVALUATION")
    print("="*60)

    # Extract test period
    test_forecast = forecast.iloc[-len(test_df):].copy()

    # Calculate point forecast metrics
    mae = mean_absolute_error(test_forecast['y'], test_forecast['yhat'])
    rmse = np.sqrt(mean_squared_error(test_forecast['y'], test_forecast['yhat']))
    mape = np.mean(np.abs((test_forecast['y'] - test_forecast['yhat']) / test_forecast['y'])) * 100

    print("\n1. POINT FORECAST METRICS:")
    print(f"   - MAE:  {mae:.2f}")
    print(f"   - RMSE: {rmse:.2f}")
    print(f"   - MAPE: {mape:.1f}%")

    # Calculate empirical coverage
    coverage_80 = np.mean(
        (test_forecast['y'] >= test_forecast['yhat_lower_80']) &
        (test_forecast['y'] <= test_forecast['yhat_upper_80'])
    )

    coverage_95 = np.mean(
        (test_forecast['y'] >= test_forecast['yhat_lower_95']) &
        (test_forecast['y'] <= test_forecast['yhat_upper_95'])
    )

    print("\n2. INITIAL CALIBRATION (Empirical Coverage):")
    print(f"   - 80% Prediction Interval: {coverage_80*100:.1f}% (Target: 80%)")
    print(f"   - 95% Prediction Interval: {coverage_95*100:.1f}% (Target: 95%)")

    # Calculate calibration errors
    error_80 = abs(coverage_80 - 0.80) * 100
    error_95 = abs(coverage_95 - 0.95) * 100

    print("\n3. CALIBRATION ERRORS:")
    print(f"   - 80% Interval Error: {error_80:.1f}%")
    print(f"   - 95% Interval Error: {error_95:.1f}%")

    # Check if calibration needed
    needs_calibration = error_80 > 2 or error_95 > 2

    if needs_calibration:
        print(f"\n⚠️  Calibration needed: Errors > 2%")
    else:
        print(f"\n✅ Calibration acceptable")

    metrics = {
        'mae': mae,
        'rmse': rmse,
        'mape': mape,
        'coverage_80_initial': coverage_80,
        'coverage_95_initial': coverage_95,
        'error_80': error_80,
        'error_95': error_95,
        'needs_calibration': needs_calibration
    }

    return metrics, test_forecast

metrics, test_forecast = evaluate_model_performance(forecast, test_df)

#step 8

def calibrate_prediction_intervals_simple(train_df, forecast, test_forecast):
    """Simple but effective calibration using residual quantiles."""

    print("\n" + "="*60)
    print("MODEL CALIBRATION (Quantile Method)")
    print("="*60)

    # Calculate residuals on training data
    train_forecast = forecast.iloc[:len(train_df)].copy()
    train_residuals = train_forecast['y'] - train_forecast['yhat']

    # Calculate residual statistics
    residual_mean = train_residuals.mean()
    residual_std = train_residuals.std()

    print(f"\nResidual Statistics:")
    print(f"  Mean: {residual_mean:.2f}")
    print(f"  Std:  {residual_std:.2f}")

    # Method 1: Simple scaling based on empirical coverage
    # Calculate what coverage we actually got on training data
    train_coverage_80 = np.mean(
        (train_forecast['y'] >= train_forecast['yhat_lower_80']) &
        (train_forecast['y'] <= train_forecast['yhat_upper_80'])
    )

    train_coverage_95 = np.mean(
        (train_forecast['y'] >= train_forecast['yhat_lower_95']) &
        (train_forecast['y'] <= train_forecast['yhat_upper_95'])
    )

    print(f"\nTraining Data Coverage:")
    print(f"  80% intervals: {train_coverage_80*100:.1f}%")
    print(f"  95% intervals: {train_coverage_95*100:.1f}%")

    # Method 2: Quantile-based calibration
    # Get empirical quantiles from absolute residuals
    abs_residuals = np.abs(train_residuals)
    empirical_80 = np.percentile(abs_residuals, 80)  # 80th percentile
    empirical_95 = np.percentile(abs_residuals, 95)  # 95th percentile

    # Current interval widths (from Prophet)
    current_width_80 = (test_forecast['yhat_upper_80'] - test_forecast['yhat_lower_80']).mean() / 2
    current_width_95 = (test_forecast['yhat_upper_95'] - test_forecast['yhat_lower_95']).mean() / 2

    # Calculate scaling factors
    scale_80 = empirical_80 / current_width_80 if current_width_80 > 0 else 1.5
    scale_95 = empirical_95 / current_width_95 if current_width_95 > 0 else 1.8

    # Apply calibration
    calibrated = test_forecast.copy()

    # Center the intervals on the prediction
    calibrated['yhat_lower_80_cal'] = calibrated['yhat'] - scale_80 * current_width_80
    calibrated['yhat_upper_80_cal'] = calibrated['yhat'] + scale_80 * current_width_80

    calibrated['yhat_lower_95_cal'] = calibrated['yhat'] - scale_95 * current_width_95
    calibrated['yhat_upper_95_cal'] = calibrated['yhat'] + scale_95 * current_width_95

    # Calculate calibrated coverage
    coverage_80_cal = np.mean(
        (calibrated['y'] >= calibrated['yhat_lower_80_cal']) &
        (calibrated['y'] <= calibrated['yhat_upper_80_cal'])
    )

    coverage_95_cal = np.mean(
        (calibrated['y'] >= calibrated['yhat_lower_95_cal']) &
        (calibrated['y'] <= calibrated['yhat_upper_95_cal'])
    )

    print(f"\nCalibration Results:")
    print(f"  Scaling factors - 80%: {scale_80:.2f}, 95%: {scale_95:.2f}")
    print(f"  Calibrated 80% Coverage: {coverage_80_cal*100:.1f}%")
    print(f"  Calibrated 95% Coverage: {coverage_95_cal*100:.1f}%")

    # Calculate improvements
    improvement_80 = abs(metrics['error_80'] - abs(coverage_80_cal - 0.80) * 100)
    improvement_95 = abs(metrics['error_95'] - abs(coverage_95_cal - 0.95) * 100)

    print(f"\nImprovement:")
    print(f"  80% error reduced by: {improvement_80:.1f}%")
    print(f"  95% error reduced by: {improvement_95:.1f}%")

    calibration_info = {
        'coverage_80_calibrated': coverage_80_cal,
        'coverage_95_calibrated': coverage_95_cal,
        'scale_80': scale_80,
        'scale_95': scale_95,
        'improvement_80': improvement_80,
        'improvement_95': improvement_95,
        'method': 'quantile_scaling'
    }

    return calibrated, calibration_info

# Apply calibration if needed
if metrics['needs_calibration']:
    calibrated_forecast, calibration_info = calibrate_prediction_intervals_simple(
        train_df, forecast, test_forecast
    )
else:
    print("\nCalibration not needed - model is well calibrated.")
    calibrated_forecast = test_forecast.copy()
    calibration_info = {
        'coverage_80_calibrated': metrics['coverage_80_initial'],
        'coverage_95_calibrated': metrics['coverage_95_initial'],
        'scale_80': 1.0,
        'scale_95': 1.0,
        'improvement_80': 0,
        'improvement_95': 0,
        'method': 'none_needed'
    }

#step 9

def visualize_results(train_df, test_df, forecast, calibrated_forecast, metrics, calibration_info):
    """Create comprehensive visualizations."""

    print("\n" + "="*60)
    print("GENERATING VISUALIZATIONS")
    print("="*60)

    fig = plt.figure(figsize=(16, 12))

    # 1. Full forecast with intervals
    ax1 = plt.subplot(2, 2, 1)
    ax1.plot(train_df['ds'], train_df['y'], 'b-', alpha=0.5, linewidth=0.8, label='Training')
    ax1.plot(test_df['ds'], test_df['y'], 'g-', alpha=0.7, linewidth=1, label='Test Actual')
    ax1.plot(forecast['ds'], forecast['yhat'], 'r--', alpha=0.8, linewidth=1, label='Forecast')

    # Plot 95% intervals
    ax1.fill_between(
        forecast['ds'],
        forecast['yhat_lower_95'],
        forecast['yhat_upper_95'],
        alpha=0.2, color='red', label='95% Interval'
    )

    ax1.set_title('Full Forecast with 95% Prediction Intervals')
    ax1.set_xlabel('Date')
    ax1.set_ylabel('Value')
    ax1.legend(loc='upper left', fontsize=9)
    ax1.grid(True, alpha=0.3)

    # 2. Test period with calibrated intervals
    ax2 = plt.subplot(2, 2, 2)
    test_dates = calibrated_forecast['ds']

    ax2.plot(test_dates, calibrated_forecast['y'], 'g-', alpha=0.9, linewidth=1.5, label='Actual')
    ax2.plot(test_dates, calibrated_forecast['yhat'], 'r--', alpha=0.9, linewidth=1.5, label='Forecast')

    # Plot calibrated intervals if available
    if 'yhat_lower_95_cal' in calibrated_forecast.columns:
        ax2.fill_between(
            test_dates,
            calibrated_forecast['yhat_lower_95_cal'],
            calibrated_forecast['yhat_upper_95_cal'],
            alpha=0.2, color='orange', label='Calibrated 95% Interval'
        )
        # Also show original intervals for comparison
        ax2.fill_between(
            test_dates,
            calibrated_forecast['yhat_lower_95'],
            calibrated_forecast['yhat_upper_95'],
            alpha=0.1, color='red', label='Original 95% Interval'
        )
    else:
        ax2.fill_between(
            test_dates,
            calibrated_forecast['yhat_lower_95'],
            calibrated_forecast['yhat_upper_95'],
            alpha=0.2, color='red', label='95% Interval'
        )

    ax2.set_title('Test Period: Actual vs Forecast')
    ax2.set_xlabel('Date')
    ax2.set_ylabel('Value')
    ax2.legend(loc='upper left', fontsize=9)
    ax2.grid(True, alpha=0.3)

    # 3. Coverage comparison
    ax3 = plt.subplot(2, 2, 3)
    categories = ['80% Interval', '95% Interval']
    initial = [metrics['coverage_80_initial']*100, metrics['coverage_95_initial']*100]

    if 'coverage_80_calibrated' in calibration_info:
        calibrated = [calibration_info['coverage_80_calibrated']*100,
                     calibration_info['coverage_95_calibrated']*100]
        targets = [80, 95]

        x = np.arange(len(categories))
        width = 0.25

        bars1 = ax3.bar(x - width, initial, width, label='Initial', color='skyblue')
        bars2 = ax3.bar(x, calibrated, width, label='Calibrated', color='lightgreen')
        bars3 = ax3.bar(x + width, targets, width, label='Target', color='orange', alpha=0.6)

        # Add value labels
        for bars in [bars1, bars2, bars3]:
            for bar in bars:
                height = bar.get_height()
                ax3.text(bar.get_x() + bar.get_width()/2., height,
                        f'{height:.1f}%', ha='center', va='bottom', fontsize=8)
    else:
        ax3.bar(categories, initial, color='skyblue', alpha=0.7)
        ax3.axhline(y=80, color='orange', linestyle='--', alpha=0.5, label='80% Target')
        ax3.axhline(y=95, color='red', linestyle='--', alpha=0.5, label='95% Target')
        ax3.legend()

    ax3.set_xlabel('Prediction Interval')
    ax3.set_ylabel('Empirical Coverage (%)')
    ax3.set_title('Coverage Rates Comparison')
    ax3.grid(True, alpha=0.3, axis='y')

    # 4. Residual analysis
    ax4 = plt.subplot(2, 2, 4)
    residuals = test_forecast['y'] - test_forecast['yhat']

    # Histogram of residuals