# -*- coding: utf-8 -*-
"""forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CT2GiL2AZglv851jpzd9V7bgX9-3D3O3
"""

# Import required DEEP LEARNING libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, Model
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error
import warnings
warnings.filterwarnings('ignore')

# Set random seeds for reproducibility
np.random.seed(42)
tf.random.set_seed(42)

print("TensorFlow Version:", tf.__version__)
print("Keras Version:", keras.__version__)


def generate_timeseries_data(n_samples=2000, seq_length=60, horizon=7, n_features=5):
    """
    Generate synthetic time series data suitable for deep learning.

    Parameters:
    - n_samples: Total number of samples
    - seq_length: Lookback window for LSTM
    - horizon: Forecast horizon
    - n_features: Number of features including target

    Returns:
    - X_train, y_train, X_test, y_test
    """
    print(f"\n{'='*60}")
    print("GENERATING SYNTHETIC TIME SERIES DATA")
    print('='*60)

    # Generate timestamps
    dates = pd.date_range(start='2022-01-01', periods=n_samples, freq='H')

    # 1. Main trend component
    trend = np.linspace(0, 100, n_samples)

    # 2. Multiple seasonalities
    # Daily seasonality (24 hours)
    daily = 20 * np.sin(2 * np.pi * np.arange(n_samples) / 24)

    # Weekly seasonality (168 hours)
    weekly = 15 * np.sin(2 * np.pi * np.arange(n_samples) / (24*7))

    # Yearly seasonality (365*24 hours)
    yearly = 10 * np.sin(2 * np.pi * np.arange(n_samples) / (24*365))

    # 3. External features
    temperature = 20 + 10 * np.sin(2 * np.pi * np.arange(n_samples) / (24*365)) + np.random.normal(0, 3, n_samples)
    humidity = 50 + 20 * np.sin(2 * np.pi * np.arange(n_samples) / (24*30)) + np.random.normal(0, 5, n_samples)
    pressure = 1000 + 10 * np.sin(2 * np.pi * np.arange(n_samples) / (24*180)) + np.random.normal(0, 2, n_samples)

    # 4. Combine to create target variable
    y = trend + daily + weekly + yearly + 0.5*temperature + 0.3*humidity + 0.1*pressure

    # Add noise
    y += np.random.normal(0, 5, n_samples)

    # 5. Create feature matrix
    features = np.column_stack([y, temperature, humidity, pressure])

    # Create sequences for LSTM
    X, y_seq = [], []
    for i in range(len(features) - seq_length - horizon):
        X.append(features[i:i+seq_length])
        y_seq.append(y[i+seq_length:i+seq_length+horizon])

    X = np.array(X)
    y_seq = np.array(y_seq)

    # Split into train/test
    split_idx = int(0.8 * len(X))
    X_train, X_test = X[:split_idx], X[split_idx:]
    y_train, y_test = y_seq[:split_idx], y_seq[split_idx:]

    # Scale the data
    scaler_X = MinMaxScaler()
    scaler_y = MinMaxScaler()

    # Reshape for scaling
    X_train_reshaped = X_train.reshape(-1, X_train.shape[-1])
    X_test_reshaped = X_test.reshape(-1, X_test.shape[-1])

    # Fit on training data
    X_train_scaled = scaler_X.fit_transform(X_train_reshaped).reshape(X_train.shape)
    X_test_scaled = scaler_X.transform(X_test_reshaped).reshape(X_test.shape)

    y_train_reshaped = y_train.reshape(-1, 1)
    y_test_reshaped = y_test.reshape(-1, 1)

    y_train_scaled = scaler_y.fit_transform(y_train_reshaped).reshape(y_train.shape)
    y_test_scaled = scaler_y.transform(y_test_reshaped).reshape(y_test.shape)

    print(f"Generated {len(X)} sequences")
    print(f"Sequence length (lookback): {seq_length}")
    print(f"Forecast horizon: {horizon}")
    print(f"Number of features: {n_features}")
    print(f"Training samples: {len(X_train)}")
    print(f"Testing samples: {len(X_test)}")
    print(f"Input shape: {X_train_scaled.shape}")
    print(f"Output shape: {y_train_scaled.shape}")

    return X_train_scaled, y_train_scaled, X_test_scaled, y_test_scaled, scaler_y

# Generate data
X_train, y_train, X_test, y_test, scaler_y = generate_timeseries_data(
    n_samples=2000,
    seq_length=60,
    horizon=7,
    n_features=4
)



def create_hybrid_lstm_attention_model(input_shape, horizon, n_features):
    """
    Create a hybrid LSTM-Attention model for time series forecasting.

    Architecture:
    1. LSTM layers for temporal pattern learning
    2. Multi-head attention for focusing on important timesteps
    3. Dense layers for final prediction
    """
    print(f"\n{'='*60}")
    print("BUILDING HYBRID LSTM-ATTENTION MODEL")
    print('='*60)

    inputs = layers.Input(shape=input_shape)

    # Part 1: LSTM layers for sequence processing
    x = layers.LSTM(128, return_sequences=True, dropout=0.2)(inputs)
    x = layers.LSTM(64, return_sequences=True, dropout=0.2)(x)

    # Part 2: Multi-head Attention mechanism
    attention_output = layers.MultiHeadAttention(
        num_heads=4,
        key_dim=32,
        dropout=0.1
    )(x, x)  # Self-attention

    # Add & Norm (Transformer-style)
    x = layers.Add()([x, attention_output])
    x = layers.LayerNormalization(epsilon=1e-6)(x)

    # Part 3: Feature extraction
    x = layers.Conv1D(32, kernel_size=3, padding='same', activation='relu')(x)
    x = layers.GlobalAveragePooling1D()(x)

    # Part 4: Dense layers for prediction
    x = layers.Dense(64, activation='relu')(x)
    x = layers.Dropout(0.2)(x)
    x = layers.Dense(32, activation='relu')(x)

    # Output layer (predict horizon steps)
    outputs = layers.Dense(horizon)(x)

    model = Model(inputs=inputs, outputs=outputs)

    # Compile model
    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=0.001),
        loss='mse',
        metrics=['mae']
    )

    model.summary()
    return model

# Create the hybrid model
input_shape = (X_train.shape[1], X_train.shape[2])  # (seq_length, n_features)
horizon = y_train.shape[1]
hybrid_model = create_hybrid_lstm_attention_model(input_shape, horizon, X_train.shape[2])



def create_simple_lstm_model(input_shape, horizon):
    """
    Create a simple LSTM model for benchmarking.
    """
    print(f"\n{'='*60}")
    print("BUILDING SIMPLE LSTM MODEL (BENCHMARK)")
    print('='*60)

    model = keras.Sequential([
        layers.LSTM(64, return_sequences=True, input_shape=input_shape),
        layers.LSTM(32),
        layers.Dense(16, activation='relu'),
        layers.Dropout(0.2),
        layers.Dense(horizon)
    ])

    model.compile(
        optimizer='adam',
        loss='mse',
        metrics=['mae']
    )

    model.summary()
    return model

# Create simple LSTM model
simple_lstm = create_simple_lstm_model(input_shape, horizon)



def train_model(model, X_train, y_train, X_val, y_val, model_name, epochs=50):
    """
    Train a model with early stopping and learning rate scheduling.
    """
    print(f"\nTraining {model_name}...")

    # Callbacks
    callbacks = [
        keras.callbacks.EarlyStopping(
            monitor='val_loss',
            patience=10,
            restore_best_weights=True
        ),
        keras.callbacks.ReduceLROnPlateau(
            monitor='val_loss',
            factor=0.5,
            patience=5,
            min_lr=1e-6
        )
    ]

    history = model.fit(
        X_train, y_train,
        validation_data=(X_val, y_val),
        epochs=epochs,
        batch_size=32,
        callbacks=callbacks,
        verbose=1
    )

    return history

# Split training data for validation
val_split = 0.2
val_size = int(len(X_train) * val_split)
X_train_final = X_train[:-val_size]
y_train_final = y_train[:-val_size]
X_val = X_train[-val_size:]
y_val = y_train[-val_size:]

# Train both models
print(f"\n{'='*60}")
print("TRAINING MODELS")
print('='*60)

# Train Hybrid Model
hybrid_history = train_model(
    hybrid_model, X_train_final, y_train_final, X_val, y_val,
    "Hybrid LSTM-Attention Model", epochs=50
)

# Train Simple LSTM Model
simple_history = train_model(
    simple_lstm, X_train_final, y_train_final, X_val, y_val,
    "Simple LSTM Model", epochs=50
)



def evaluate_model(model, X_test, y_test, scaler, model_name):
    """
    Evaluate model performance and return metrics.
    """
    print(f"\nEvaluating {model_name}...")

    # Make predictions
    y_pred_scaled = model.predict(X_test, verbose=0)

    # Inverse transform predictions
    y_pred_reshaped = y_pred_scaled.reshape(-1, 1)
    y_pred = scaler.inverse_transform(y_pred_reshaped).reshape(y_pred_scaled.shape)

    # Inverse transform actual values
    y_actual_reshaped = y_test.reshape(-1, 1)
    y_actual = scaler.inverse_transform(y_actual_reshaped).reshape(y_test.shape)

    # Calculate metrics for each forecast horizon
    metrics = {}

    # For each horizon step
    for h in range(y_test.shape[1]):
        y_actual_h = y_actual[:, h]
        y_pred_h = y_pred[:, h]

        # Calculate metrics
        mae = mean_absolute_error(y_actual_h, y_pred_h)
        rmse = np.sqrt(mean_squared_error(y_actual_h, y_pred_h))
        mape = np.mean(np.abs((y_actual_h - y_pred_h) / y_actual_h)) * 100

        # Calculate directional accuracy
        actual_direction = np.diff(y_actual_h) > 0
        pred_direction = np.diff(y_pred_h) > 0
        directional_accuracy = np.mean(actual_direction == pred_direction) * 100 if len(actual_direction) > 0 else 0

        metrics[f'horizon_{h+1}'] = {
            'MAE': mae,
            'RMSE': rmse,
            'MAPE': mape,
            'Directional_Accuracy': directional_accuracy
        }

    # Overall metrics (average across horizons)
    y_actual_flat = y_actual.flatten()
    y_pred_flat = y_pred.flatten()

    metrics['overall'] = {
        'MAE': mean_absolute_error(y_actual_flat, y_pred_flat),
        'RMSE': np.sqrt(mean_squared_error(y_actual_flat, y_pred_flat)),
        'MAPE': np.mean(np.abs((y_actual_flat - y_pred_flat) / y_actual_flat)) * 100,
        'Directional_Accuracy': np.mean(
            (np.diff(y_actual_flat) > 0) == (np.diff(y_pred_flat) > 0)
        ) * 100 if len(y_actual_flat) > 1 else 0
    }

    return metrics, y_pred, y_actual

print(f"\n{'='*60}")
print("MODEL EVALUATION")
print('='*60)

# Evaluate Hybrid Model
hybrid_metrics, hybrid_pred, hybrid_actual = evaluate_model(
    hybrid_model, X_test, y_test, scaler_y, "Hybrid LSTM-Attention Model"
)

# Evaluate Simple LSTM Model
simple_metrics, simple_pred, simple_actual = evaluate_model(
    simple_lstm, X_test, y_test, scaler_y, "Simple LSTM Model"
)



def create_comparison_table(hybrid_metrics, simple_metrics):
    """
    Create a comparison table of model performance.
    """
    print(f"\n{'='*60}")
    print("MODEL PERFORMANCE COMPARISON")
    print('='*60)

    comparison_data = []

    # Compare overall metrics
    for metric in ['MAE', 'RMSE', 'MAPE', 'Directional_Accuracy']:
        hybrid_val = hybrid_metrics['overall'][metric]
        simple_val = simple_metrics['overall'][metric]

        # Calculate improvement
        if metric in ['MAE', 'RMSE', 'MAPE']:
            improvement = ((simple_val - hybrid_val) / simple_val) * 100
            direction = "↓" if improvement > 0 else "↑"
        else:  # Directional Accuracy
            improvement = ((hybrid_val - simple_val) / simple_val) * 100
            direction = "↑" if improvement > 0 else "↓"

        comparison_data.append({
            'Metric': metric,
            'Hybrid Model': f"{hybrid_val:.4f}",
            'Simple LSTM': f"{simple_val:.4f}",
            'Improvement': f"{improvement:.2f}% {direction}",
            'Better': 'Hybrid' if (
                (metric in ['MAE', 'RMSE', 'MAPE'] and hybrid_val < simple_val) or
                (metric == 'Directional_Accuracy' and hybrid_val > simple_val)
            ) else 'LSTM'
        })

    # Create DataFrame
    comparison_df = pd.DataFrame(comparison_data)

    # Display table
    print("\n" + comparison_df.to_string(index=False))

    return comparison_df

# Create comparison table
comparison_df = create_comparison_table(hybrid_metrics, simple_metrics)



def create_visualizations(hybrid_history, simple_history, hybrid_pred, simple_pred,
                          hybrid_actual, simple_actual, comparison_df):
    """
    Create comprehensive visualizations for analysis.
    """
    print(f"\n{'='*60}")
    print("GENERATING VISUALIZATIONS")
    print('='*60)

    fig = plt.figure(figsize=(18, 12))

    # 1. Training History Comparison
    ax1 = plt.subplot(2, 3, 1)
    ax1.plot(hybrid_history.history['loss'], label='Hybrid Train Loss', color='blue')
    ax1.plot(hybrid_history.history['val_loss'], label='Hybrid Val Loss', color='blue', linestyle='--')
    ax1.plot(simple_history.history['loss'], label='LSTM Train Loss', color='red')
    ax1.plot(simple_history.history['val_loss'], label='LSTM Val Loss', color='red', linestyle='--')
    ax1.set_title('Training History Comparison')
    ax1.set_xlabel('Epoch')
    ax1.set_ylabel('Loss (MSE)')
    ax1.legend()
    ax1.grid(True, alpha=0.3)

    # 2. Predictions vs Actual (Hybrid Model)
    ax2 = plt.subplot(2, 3, 2)
    sample_idx = 50  # Plot one sample
    timesteps = np.arange(hybrid_pred.shape[1])
    ax2.plot(timesteps, hybrid_actual[sample_idx], 'g-', label='Actual', linewidth=2)
    ax2.plot(timesteps, hybrid_pred[sample_idx], 'r--', label='Hybrid Prediction', linewidth=2)
    ax2.set_title('Hybrid Model: Predictions vs Actual')
    ax2.set_xlabel('Forecast Horizon')
    ax2.set_ylabel('Value')
    ax2.legend()
    ax2.grid(True, alpha=0.3)

    # 3. Predictions vs Actual (Simple LSTM)
    ax3 = plt.subplot(2, 3, 3)
    ax3.plot(timesteps, simple_actual[sample_idx], 'g-', label='Actual', linewidth=2)
    ax3.plot(timesteps, simple_pred[sample_idx], 'b--', label='LSTM Prediction', linewidth=2)
    ax3.set_title('Simple LSTM: Predictions vs Actual')
    ax3.set_xlabel('Forecast Horizon')
    ax3.set_ylabel('Value')
    ax3.legend()
    ax3.grid(True, alpha=0.3)

    # 4. Error Distribution
    ax4 = plt.subplot(2, 3, 4)
    hybrid_errors = (hybrid_pred - hybrid_actual).flatten()
    simple_errors = (simple_pred - simple_actual).flatten()

    ax4.hist(hybrid_errors, bins=50, alpha=0.5, label='Hybrid Errors', color='blue')
    ax4.hist(simple_errors, bins=50, alpha=0.5, label='LSTM Errors', color='red')
    ax4.axvline(x=0, color='black', linestyle='--', linewidth=1)
    ax4.set_title('Error Distribution Comparison')
    ax4.set_xlabel('Prediction Error')
    ax4.set_ylabel('Frequency')
    ax4.legend()
    ax4.grid(True, alpha=0.3)

    # 5. Metric Comparison Bar Chart
    ax5 = plt.subplot(2, 3, 5)
    metrics = ['MAE', 'RMSE', 'MAPE']
    hybrid_vals = [hybrid_metrics['overall'][m] for m in metrics]
    simple_vals = [simple_metrics['overall'][m] for m in metrics]

    x = np.arange(len(metrics))
    width = 0.35

    ax5.bar(x - width/2, hybrid_vals, width, label='Hybrid Model', color='blue')
    ax5.bar(x + width/2, simple_vals, width, label='Simple LSTM', color='red')

    ax5.set_xlabel('Metrics')
    ax5.set_ylabel('Value')
    ax5.set_title('Model Performance Comparison')
    ax5.set_xticks(x)
    ax5.set_xticklabels(metrics)
    ax5.legend()
    ax5.grid(True, alpha=0.3)

    # 6. Directional Accuracy Comparison
    ax6 = plt.subplot(2, 3, 6)
    models = ['Hybrid Model', 'Simple LSTM']
    accuracies = [
        hybrid_metrics['overall']['Directional_Accuracy'],
        simple_metrics['overall']['Directional_Accuracy']
    ]

    bars = ax6.bar(models, accuracies, color=['blue', 'red'])
    ax6.set_ylabel('Directional Accuracy (%)')
    ax6.set_title('Directional Accuracy Comparison')
    ax6.set_ylim([0, 100])
    ax6.grid(True, alpha=0.3)

    # Add value labels on bars
    for bar, accuracy in zip(bars, accuracies):
        height = bar.get_height()
        ax6.text(bar.get_x() + bar.get_width()/2., height,
                f'{accuracy:.1f}%', ha='center', va='bottom')

    plt.tight_layout()
    plt.savefig('model_comparison_results.png', dpi=150, bbox_inches='tight')
    plt.show()

    print("Visualizations saved to 'model_comparison_results.png'")

# Create visualizations
create_visualizations(hybrid_history, simple_history, hybrid_pred, simple_pred,
                      hybrid_actual, simple_actual, comparison_df)



def visualize_attention(model, X_sample, seq_length):
    """
    Visualize attention weights to understand what the model focuses on.
    """
    print(f"\n{'='*60}")
    print("ATTENTION MECHANISM VISUALIZATION")
    print('='*60)

    try:
        # Create a model that outputs attention weights
        attention_layer = model.get_layer('multi_head_attention')

        # Get attention outputs
        attention_model = Model(
            inputs=model.input,
            outputs=attention_layer.output
        )

        # Get attention weights for a sample
        sample = X_sample[np.newaxis, ...]
        attention_output = attention_model.predict(sample, verbose=0)

        # Visualize attention weights
        fig, ax = plt.subplots(figsize=(10, 8))

        # For multi-head attention, we have multiple attention heads
        if len(attention_output.shape) == 4:
            # Take first head for visualization
            attention_weights = attention_output[0, :, :, 0]
        else:
            attention_weights = attention_output[0]

        # Plot attention heatmap
        im = ax.imshow(attention_weights, cmap='viridis', aspect='auto')
        ax.set_xlabel('Key Sequence Position')
        ax.set_ylabel('Query Sequence Position')
        ax.set_title('Attention Weights Heatmap (First Head)')

        # Add colorbar
        plt.colorbar(im, ax=ax)

        # Add timestep labels
        ax.set_xticks(np.arange(seq_length))
        ax.set_yticks(np.arange(seq_length))
        ax.set_xticklabels([f't-{seq_length-i}' for i in range(seq_length)])
        ax.set_yticklabels([f't-{seq_length-i}' for i in range(seq_length)])

        plt.tight_layout()
        plt.savefig('attention_visualization.png', dpi=150, bbox_inches='tight')
        plt.show()

        print("Attention visualization saved to 'attention_visualization.png'")

    except Exception as e:
        print(f"Could not extract attention weights: {e}")
        print("Creating simplified attention analysis...")

        # Alternative: Analyze which timesteps are most important
        feature_importance = np.std(X_sample, axis=1)

        fig, ax = plt.subplots(figsize=(10, 6))
        ax.bar(range(len(feature_importance)), feature_importance)
        ax.set_xlabel('Timestep (from oldest to newest)')
        ax.set_ylabel('Feature Variability')
        ax.set_title('Input Sequence Importance Analysis')
        ax.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.savefig('sequence_importance.png', dpi=150, bbox_inches='tight')
        plt.show()

        print("Sequence importance analysis saved to 'sequence_importance.png'")

# Visualize attention for a sample
sample_idx = 0
visualize_attention(hybrid_model, X_test[sample_idx], X_test.shape[1])



def generate_final_report(hybrid_metrics, simple_metrics, comparison_df):
    """
    Generate final report with all findings.
    """
    print(f"\n{'='*60}")
    print("FINAL REPORT GENERATION")
    print('='*60)

    report = f"""

    {comparison_df.to_string(index=False)}

    # Add findings based on comparison
    hybrid_better = 0
    lstm_better = 0

    for i, row in comparison_df.iterrows():
        if row['Better'] == 'Hybrid':
            hybrid_better += 1
            report += f"    • {row['Metric']}: Hybrid model outperforms by {row['Improvement']}\n"
        else:
            lstm_better += 1
            report += f"    • {row['Metric']}: Simple LSTM performs better\n"

    report += f"""


   # Save report to file
    with open('project_report.txt', 'w') as f:
        f.write(report)

    print(report)
    print("\nFull report saved to 'project_report.txt'")
    print("\n" + "="*60)
    print("PROJECT COMPLETED SUCCESSFULLY!")
    print("="*60)

    return report

# Generate final report
final_report = generate_final_report(hybrid_metrics, simple_metrics, comparison_df)

print(f"\n{'='*60}")
print("SAVING MODELS AND RESULTS")
print('='*60)

# Save models
hybrid_model.save('hybrid_lstm_attention_model.h5')
simple_lstm.save('simple_lstm_model.h5')
print("✓ Models saved as .h5 files")

# Save metrics to CSV
metrics_df = pd.DataFrame({
    'Model': ['Hybrid LSTM-Attention', 'Simple LSTM'],
    'MAE': [hybrid_metrics['overall']['MAE'], simple_metrics['overall']['MAE']],
    'RMSE': [hybrid_metrics['overall']['RMSE'], simple_metrics['overall']['RMSE']],
    'MAPE': [hybrid_metrics['overall']['MAPE'], simple_metrics['overall']['MAPE']],
    'Directional_Accuracy': [hybrid_metrics['overall']['Directional_Accuracy'],
                           simple_metrics['overall']['Directional_Accuracy']]
})

metrics_df.to_csv('model_metrics.csv', index=False)
print("✓ Metrics saved to 'model_metrics.csv'")

# Save comparison table
comparison_df.to_csv('model_comparison.csv', index=False)
print("✓ Comparison table saved to 'model_comparison.csv'")

print("\n" + "="*60)
print("ALL FILES SAVED:")
print("="*60)
print("1. hybrid_lstm_attention_model.h5")
print("2. simple_lstm_model.h5")
print("3. model_metrics.csv")
print("4. model_comparison.csv")
print("5. project_report.txt")
print("6. model_comparison_results.png")
print("7. attention_visualization.png")
print("="*60)