# -*- coding: utf-8 -*-
"""forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CT2GiL2AZglv851jpzd9V7bgX9-3D3O3
"""

# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from prophet import Prophet
from sklearn.metrics import mean_absolute_error, mean_squared_error
import warnings
warnings.filterwarnings('ignore')
from sklearn.isotonic import IsotonicRegression
from scipy import stats
import json
from datetime import datetime, timedelta
import random

# Set random seeds for reproducibility
np.random.seed(42)
random.seed(42)

# Generate synthetic time series dataset with daily frequency (2+ years)
def generate_synthetic_dataset():
    """
    Generate a synthetic time series dataset with:
    - Daily data for 2+ years (800+ days)
    - Multiple seasonal patterns (daily, weekly, yearly)
    - Trend component
    - External regressors (weather and economic indicators)
    - Noise
    """
    # Create date range: 800 days starting from 2022-01-01
    dates = pd.date_range(start='2022-01-01', periods=800, freq='D')

    # Base trend (linear with some changes)
    trend = np.linspace(100, 200, len(dates))

    # Add trend changepoints
    trend[300:500] += np.linspace(0, 50, 200)
    trend[500:] += np.linspace(50, 0, 300)

    # Seasonal patterns
    # Yearly seasonality (365-day cycle)
    yearly_season = 20 * np.sin(2 * np.pi * np.arange(len(dates)) / 365)

    # Weekly seasonality (7-day cycle)
    weekly_season = 10 * np.sin(2 * np.pi * np.arange(len(dates)) / 7)

    # Daily pattern (intra-day pattern approximated as 4 cycles per day)
    daily_season = 5 * np.sin(2 * np.pi * np.arange(len(dates)) / (1/4))

    # Generate external regressors
    # 1. Temperature (seasonal with noise)
    temperature = 15 + 10 * np.sin(2 * np.pi * np.arange(len(dates)) / 365) + np.random.normal(0, 3, len(dates))

    # 2. Economic indicator (slow-moving trend with some volatility)
    economic_indicator = np.cumsum(np.random.normal(0.01, 0.5, len(dates))) + 100

    # 3. Holiday indicator (spikes during "holiday" periods)
    holiday_effect = np.zeros(len(dates))
    for i in range(len(dates)):
        # Create synthetic holidays around specific dates
        if dates[i].month == 12 and dates[i].day <= 25 and dates[i].day >= 20:
            holiday_effect[i] = np.random.normal(15, 3)
        elif dates[i].month == 7 and dates[i].day <= 7 and dates[i].day >= 1:
            holiday_effect[i] = np.random.normal(10, 2)

    # Add special events/outliers
    outliers = np.zeros(len(dates))
    outlier_indices = random.sample(range(50, 750), 10)
    for idx in outlier_indices:
        outliers[idx] = np.random.normal(30, 10)

    # Combine all components with weights
    y = (trend +
         yearly_season +
         weekly_season +
         daily_season * 0.5 +  # Smaller daily effect
         temperature * 0.3 +  # Temperature effect
         economic_indicator * 0.1 +  # Economic effect
         holiday_effect +
         outliers +
         np.random.normal(0, 5, len(dates)))  # Random noise

    # Create DataFrame
    df = pd.DataFrame({
        'ds': dates,
        'y': y,
        'temperature': temperature,
        'economic_indicator': economic_indicator,
        'holiday_effect': holiday_effect,
        'is_holiday': (holiday_effect > 5).astype(int)
    })

    return df

# Generate and save dataset
print("Generating synthetic dataset...")
synthetic_df = generate_synthetic_dataset()
print(f"Dataset shape: {synthetic_df.shape}")
print(f"Date range: {synthetic_df['ds'].min()} to {synthetic_df['ds'].max()}")
print(f"Total days: {len(synthetic_df)}")

# Explore dataset characteristics
def explore_dataset(df):
    """Explore and visualize the synthetic dataset."""

    print("\n" + "="*60)
    print("DATASET EXPLORATION")
    print("="*60)

    # Basic statistics
    print("\n1. BASIC STATISTICS:")
    print(f"   - Mean target value: {df['y'].mean():.2f}")
    print(f"   - Std target value: {df['y'].std():.2f}")
    print(f"   - Min target value: {df['y'].min():.2f}")
    print(f"   - Max target value: {df['y'].max():.2f}")

    # Seasonality check
    print("\n2. SEASONALITY DETECTION:")
    print("   - Data exhibits daily, weekly, and yearly patterns")
    print("   - External regressors: temperature, economic indicator, holiday effect")

    # Visualize the time series
    fig, axes = plt.subplots(2, 2, figsize=(15, 10))

    # Full time series
    axes[0, 0].plot(df['ds'], df['y'], label='Target (y)', alpha=0.7)
    axes[0, 0].set_title('Full Time Series (Target Variable)')
    axes[0, 0].set_xlabel('Date')
    axes[0, 0].set_ylabel('Value')
    axes[0, 0].legend()
    axes[0, 0].grid(True, alpha=0.3)

    # Last 60 days for detailed view
    axes[0, 1].plot(df['ds'][-60:], df['y'][-60:], label='Last 60 days', color='orange')
    axes[0, 1].set_title('Recent 60 Days (Detailed View)')
    axes[0, 1].set_xlabel('Date')
    axes[0, 1].set_ylabel('Value')
    axes[0, 1].legend()
    axes[0, 1].grid(True, alpha=0.3)

    # External regressors
    axes[1, 0].plot(df['ds'], df['temperature'], label='Temperature', alpha=0.7)
    axes[1, 0].plot(df['ds'], df['economic_indicator'], label='Economic Indicator', alpha=0.7)
    axes[1, 0].set_title('External Regressors')
    axes[1, 0].set_xlabel('Date')
    axes[1, 0].set_ylabel('Value')
    axes[1, 0].legend()
    axes[1, 0].grid(True, alpha=0.3)

    # Holiday effects
    holiday_dates = df[df['is_holiday'] == 1]['ds']
    holiday_values = df[df['is_holiday'] == 1]['y']
    axes[1, 1].scatter(holiday_dates, holiday_values,
                       color='red', s=50, alpha=0.7, label='Holidays')
    axes[1, 1].plot(df['ds'], df['y'], alpha=0.3, label='Full Series')
    axes[1, 1].set_title('Holiday Effects on Target Variable')
    axes[1, 1].set_xlabel('Date')
    axes[1, 1].set_ylabel('Value')
    axes[1, 1].legend()
    axes[1, 1].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig('time_series_visualization.png', dpi=300, bbox_inches='tight')
    plt.show()

    # Correlation analysis
    print("\n3. CORRELATION ANALYSIS:")
    correlation_matrix = df[['y', 'temperature', 'economic_indicator', 'holiday_effect']].corr()
    print("\nCorrelation Matrix:")
    print(correlation_matrix)

# Explore the dataset
explore_dataset(synthetic_df)

# Prepare data for Prophet
def prepare_prophet_data(df, train_test_split=0.8):
    """
    Prepare data for Prophet modeling with train-test split.

    Parameters:
    df: DataFrame with time series data
    train_test_split: Proportion of data for training

    Returns:
    train_df, test_df, full_df formatted for Prophet
    """
    # Prophet requires columns named 'ds' (datetime) and 'y' (target)
    prophet_train_df = df[['ds', 'y']].copy()

    # Add external regressors
    prophet_train_df['temperature'] = df['temperature']
    prophet_train_df['economic_indicator'] = df['economic_indicator']

    # Split into train and test
    split_idx = int(len(prophet_train_df) * train_test_split)
    train_df = prophet_train_df.iloc[:split_idx].copy()
    test_df = prophet_train_df.iloc[split_idx:].copy()

    # Create holiday dataframe
    holiday_df = df[df['is_holiday'] == 1][['ds']].copy()
    holiday_df['holiday'] = 'synthetic_holiday'

    print(f"\nTrain set size: {len(train_df)} days ({train_df['ds'].min()} to {train_df['ds'].max()})")
    print(f"Test set size: {len(test_df)} days ({test_df['ds'].min()} to {test_df['ds'].max()})")

    return train_df, test_df, holiday_df

# Prepare the data
train_df, test_df, holiday_df = prepare_prophet_data(synthetic_df)

# Rolling origin cross-validation for time series
def rolling_origin_cv(df, initial_train_size=365, horizon=30, step=30):
    """
    Perform rolling origin cross-validation for time series.

    Parameters:
    df: Full dataset
    initial_train_size: Initial training window size in days
    horizon: Forecast horizon in days
    step: Step size between CV folds in days

    Returns:
    cv_results: DataFrame with CV metrics
    """
    cv_results = []
    total_points = len(df)

    print("\n" + "="*60)
    print("ROLLING ORIGIN CROSS-VALIDATION")
    print("="*60)

    fold_num = 1
    start_idx = initial_train_size

    while start_idx + horizon <= total_points:
        # Split train and validation
        train_cv = df.iloc[:start_idx].copy()
        val_cv = df.iloc[start_idx:start_idx + horizon].copy()

        # Initialize and fit Prophet model
        model_cv = Prophet(
            yearly_seasonality=True,
            weekly_seasonality=True,
            daily_seasonality=True,
            holidays=holiday_df,
            changepoint_prior_scale=0.05,  # Initial guess
            seasonality_prior_scale=10,
            holidays_prior_scale=10,
            seasonality_mode='additive'
        )

        # Add external regressors
        model_cv.add_regressor('temperature')
        model_cv.add_regressor('economic_indicator')

        # Fit model
        model_cv.fit(train_cv)

        # Create future dataframe for validation period
        future_cv = model_cv.make_future_dataframe(periods=horizon)
        future_cv = future_cv.merge(
            df[['ds', 'temperature', 'economic_indicator']],
            on='ds',
            how='left'
        )

        # Forecast
        forecast_cv = model_cv.predict(future_cv)

        # Extract validation predictions
        val_pred = forecast_cv.iloc[-horizon:][['ds', 'yhat', 'yhat_lower', 'yhat_upper']]
        val_actual = val_cv[['ds', 'y']]

        # Merge predictions with actuals
        val_results = pd.merge(val_pred, val_actual, on='ds')

        # Calculate metrics
        mae = mean_absolute_error(val_results['y'], val_results['yhat'])
        rmse = np.sqrt(mean_squared_error(val_results['y'], val_results['yhat']))

        # Store results
        cv_results.append({
            'fold': fold_num,
            'train_start': train_cv['ds'].min(),
            'train_end': train_cv['ds'].max(),
            'val_start': val_cv['ds'].min(),
            'val_end': val_cv['ds'].max(),
            'mae': mae,
            'rmse': rmse
        })

        print(f"Fold {fold_num}: Train: {train_cv['ds'].min().date()} to {train_cv['ds'].max().date()}, "
              f"Val: {val_cv['ds'].min().date()} to {val_cv['ds'].max().date()}, "
              f"MAE: {mae:.2f}, RMSE: {rmse:.2f}")

        fold_num += 1
        start_idx += step

    cv_results_df = pd.DataFrame(cv_results)

    print(f"\nCross-validation completed: {len(cv_results)} folds")
    print(f"Average MAE: {cv_results_df['mae'].mean():.2f}")
    print(f"Average RMSE: {cv_results_df['rmse'].mean():.2f}")

    return cv_results_df

# Perform cross-validation
cv_results = rolling_origin_cv(train_df, initial_train_size=365, horizon=60, step=30)

# Hyperparameter tuning
def tune_prophet_hyperparameters(train_df, holiday_df, n_iterations=20):
    """
    Tune Prophet hyperparameters using simple grid search.

    Parameters:
    train_df: Training data
    holiday_df: Holiday data
    n_iterations: Number of parameter combinations to try

    Returns:
    best_params: Best hyperparameters
    """
    # Parameter grid
    param_grid = {
        'changepoint_prior_scale': [0.001, 0.01, 0.05, 0.1, 0.5],
        'seasonality_prior_scale': [1, 5, 10, 20, 30],
        'holidays_prior_scale': [1, 5, 10, 20],
        'seasonality_mode': ['additive', 'multiplicative']
    }

    # Split for validation during tuning
    tune_train = train_df.iloc[:int(len(train_df) * 0.8)]
    tune_val = train_df.iloc[int(len(train_df) * 0.8):]

    best_score = float('inf')
    best_params = None
    results = []

    print("\n" + "="*60)
    print("HYPERPARAMETER TUNING")
    print("="*60)

    # Simple random search
    for i in range(n_iterations):
        # Randomly sample parameters
        params = {
            'changepoint_prior_scale': np.random.choice(param_grid['changepoint_prior_scale']),
            'seasonality_prior_scale': np.random.choice(param_grid['seasonality_prior_scale']),
            'holidays_prior_scale': np.random.choice(param_grid['holidays_prior_scale']),
            'seasonality_mode': np.random.choice(param_grid['seasonality_mode'])
        }

        try:
            # Initialize model with current parameters
            model_tune = Prophet(
                yearly_seasonality=True,
                weekly_seasonality=True,
                daily_seasonality=True,
                holidays=holiday_df,
                changepoint_prior_scale=params['changepoint_prior_scale'],
                seasonality_prior_scale=params['seasonality_prior_scale'],
                holidays_prior_scale=params['holidays_prior_scale'],
                seasonality_mode=params['seasonality_mode']
            )

            # Add external regressors
            model_tune.add_regressor('temperature')
            model_tune.add_regressor('economic_indicator')

            # Fit on training portion
            model_tune.fit(tune_train)

            # Create future dataframe
            future_tune = model_tune.make_future_dataframe(periods=len(tune_val))
            future_tune = future_tune.merge(
                train_df[['ds', 'temperature', 'economic_indicator']],
                on='ds',
                how='left'
            )

            # Predict
            forecast_tune = model_tune.predict(future_tune)

            # Extract validation predictions
            val_pred = forecast_tune.iloc[-len(tune_val):]['yhat'].values
            val_actual = tune_val['y'].values

            # Calculate RMSE
            rmse = np.sqrt(mean_squared_error(val_actual, val_pred))

            results.append({
                'iteration': i + 1,
                'params': params,
                'rmse': rmse
            })

            print(f"Iteration {i+1}: RMSE = {rmse:.2f}, Params = {params}")

            # Update best parameters
            if rmse < best_score:
                best_score = rmse
                best_params = params

        except Exception as e:
            print(f"Iteration {i+1} failed: {e}")
            continue

    results_df = pd.DataFrame(results)
    print(f"\nBest RMSE: {best_score:.2f}")
    print(f"Best parameters: {best_params}")

    return best_params

# Tune hyperparameters
best_params = tune_prophet_hyperparameters(train_df, holiday_df, n_iterations=15)

# Train final model with best hyperparameters
def train_final_model(train_df, test_df, holiday_df, best_params):
    """
    Train final Prophet model with tuned hyperparameters.

    Parameters:
    train_df: Training data
    test_df: Test data
    holiday_df: Holiday data
    best_params: Best hyperparameters from tuning

    Returns:
    model: Trained Prophet model
    forecast: Forecast results
    """
    print("\n" + "="*60)
    print("TRAINING FINAL MODEL")
    print("="*60)

    # Initialize model with best parameters
    model = Prophet(
        yearly_seasonality=True,
        weekly_seasonality=True,
        daily_seasonality=True,
        holidays=holiday_df,
        changepoint_prior_scale=best_params['changepoint_prior_scale'],
        seasonality_prior_scale=best_params['seasonality_prior_scale'],
        holidays_prior_scale=best_params['holidays_prior_scale'],
        seasonality_mode=best_params['seasonality_mode'],
        interval_width=0.95,  # For 95% prediction intervals
        mcmc_samples=0  # Set to 300 for full uncertainty estimation (slower)
    )

    # Add external regressors
    model.add_regressor('temperature')
    model.add_regressor('economic_indicator')

    # Fit model on full training data
    print("Fitting model...")
    model.fit(train_df)

    # Create future dataframe for test period
    future = model.make_future_dataframe(periods=len(test_df))

    # Add external regressors to future dataframe
    future_test = test_df[['ds', 'temperature', 'economic_indicator']].copy()
    future_test.columns = ['ds', 'temperature', 'economic_indicator']
    future = future.merge(future_test, on='ds', how='left')

    # Fill any missing values in regressors
    future['temperature'] = future['temperature'].fillna(future['temperature'].mean())
    future['economic_indicator'] = future['economic_indicator'].fillna(future['economic_indicator'].mean())

    # Generate forecast
    print("Generating forecasts...")
    forecast = model.predict(future)

    # Add actual values to forecast for comparison
    forecast = forecast.merge(
        pd.concat([train_df[['ds', 'y']], test_df[['ds', 'y']]]),
        on='ds',
        how='left'
    )

    # Calculate 80% prediction intervals (Prophet provides 95% by default)
    # We'll compute 80% intervals based on the standard deviation
    forecast['yhat_lower_80'] = forecast['yhat'] - 1.28 * (forecast['yhat_upper'] - forecast['yhat_lower']) / (2 * 1.96)
    forecast['yhat_upper_80'] = forecast['yhat'] + 1.28 * (forecast['yhat_upper'] - forecast['yhat_lower']) / (2 * 1.96)

    print("Model training complete!")

    return model, forecast

# Train final model
model, forecast = train_final_model(train_df, test_df, holiday_df, best_params)

# Evaluate model performance and calibration
def evaluate_model_performance(forecast, test_df):
    """
    Evaluate model performance and calibration of prediction intervals.

    Parameters:
    forecast: Forecast results
    test_df: Test data

    Returns:
    metrics: Dictionary with evaluation metrics
    """
    print("\n" + "="*60)
    print("MODEL EVALUATION")
    print("="*60)

    # Extract test period forecasts
    test_forecast = forecast.iloc[-len(test_df):].copy()

    # Calculate point forecast metrics
    mae = mean_absolute_error(test_forecast['y'], test_forecast['yhat'])
    rmse = np.sqrt(mean_squared_error(test_forecast['y'], test_forecast['yhat']))
    mape = np.mean(np.abs((test_forecast['y'] - test_forecast['yhat']) / test_forecast['y'])) * 100

    print(f"\n1. POINT FORECAST METRICS:")
    print(f"   - MAE (Mean Absolute Error): {mae:.2f}")
    print(f"   - RMSE (Root Mean Square Error): {rmse:.2f}")
    print(f"   - MAPE (Mean Absolute Percentage Error): {mape:.2f}%")

    # Calculate empirical coverage rates
    # For 80% interval
    coverage_80 = np.mean(
        (test_forecast['y'] >= test_forecast['yhat_lower_80']) &
        (test_forecast['y'] <= test_forecast['yhat_upper_80'])
    )

    # For 95% interval
    coverage_95 = np.mean(
        (test_forecast['y'] >= test_forecast['yhat_lower']) &
        (test_forecast['y'] <= test_forecast['yhat_upper'])
    )

    print(f"\n2. INITIAL CALIBRATION (Empirical Coverage):")
    print(f"   - 80% Prediction Interval Coverage: {coverage_80*100:.2f}% (Target: 80%)")
    print(f"   - 95% Prediction Interval Coverage: {coverage_95*100:.2f}% (Target: 95%)")

    # Calculate calibration error
    calibration_error_80 = abs(coverage_80 - 0.80) * 100
    calibration_error_95 = abs(coverage_95 - 0.95) * 100

    print(f"\n3. CALIBRATION ERRORS:")
    print(f"   - 80% Interval Error: {calibration_error_80:.2f}%")
    print(f"   - 95% Interval Error: {calibration_error_95:.2f}%")

    # Check if calibration is poor (error > 2%)
    needs_calibration = calibration_error_80 > 2 or calibration_error_95 > 2

    if needs_calibration:
        print(f"\n⚠️  Calibration needed: At least one interval error > 2%")
    else:
        print(f"\n✅ Calibration acceptable: All errors ≤ 2%")

    metrics = {
        'mae': mae,
        'rmse': rmse,
        'mape': mape,
        'coverage_80_initial': coverage_80,
        'coverage_95_initial': coverage_95,
        'calibration_error_80': calibration_error_80,
        'calibration_error_95': calibration_error_95,
        'needs_calibration': needs_calibration
    }

    return metrics, test_forecast

# Evaluate initial model
metrics, test_forecast = evaluate_model_performance(forecast, test_df)

# Implement calibration using isotonic regression
def calibrate_prediction_intervals(model, forecast, train_df, test_forecast):
    """
    Calibrate prediction intervals using isotonic regression on residuals.

    Parameters:
    model: Trained Prophet model
    forecast: Forecast results
    train_df: Training data
    test_forecast: Test forecast results

    Returns:
    calibrated_forecast: Forecast with calibrated intervals
    calibration_info: Information about calibration process
    """
    print("\n" + "="*60)
    print("MODEL CALIBRATION")
    print("="*60)

    # Calculate residuals on training data
    train_forecast = forecast.iloc[:len(train_df)].copy()
    train_residuals = train_forecast['y'] - train_forecast['yhat']

    # Calculate standard deviation of residuals
    residual_std = train_residuals.std()

    # Get uncertainty from model (standard deviation of predictions)
    train_uncertainty = (train_forecast['yhat_upper'] - train_forecast['yhat_lower']) / (2 * 1.96)

    # Calculate normalized residuals (residual divided by uncertainty)
    normalized_residuals = train_residuals / train_uncertainty

    # Sort for isotonic regression
    sorted_indices = np.argsort(normalized_residuals)
    sorted_residuals = normalized_residuals.iloc[sorted_indices].values

    # Create empirical quantiles
    n = len(sorted_residuals)
    empirical_quantiles = np.arange(1, n + 1) / (n + 1)

    # Fit isotonic regression
    iso_reg = IsotonicRegression(out_of_bounds='clip')
    iso_reg.fit(sorted_residuals, stats.norm.ppf(empirical_quantiles))

    # Apply calibration to test set
    test_uncertainty = (test_forecast['yhat_upper'] - test_forecast['yhat_lower']) / (2 * 1.96)

    # Get calibrated z-scores for different confidence levels
    calibrated_z_80 = iso_reg.predict([0])[0] * 1.28 / stats.norm.ppf(0.9)
    calibrated_z_95 = iso_reg.predict([0])[0] * 1.96 / stats.norm.ppf(0.975)

    # Calculate calibrated intervals
    calibrated_forecast = test_forecast.copy()

    # For 80% interval
    calibrated_forecast['yhat_lower_80_calibrated'] = (
        calibrated_forecast['yhat'] - calibrated_z_80 * test_uncertainty
    )
    calibrated_forecast['yhat_upper_80_calibrated'] = (
        calibrated_forecast['yhat'] + calibrated_z_80 * test_uncertainty
    )

    # For 95% interval
    calibrated_forecast['yhat_lower_95_calibrated'] = (
        calibrated_forecast['yhat'] - calibrated_z_95 * test_uncertainty
    )
    calibrated_forecast['yhat_upper_95_calibrated'] = (
        calibrated_forecast['yhat'] + calibrated_z_95 * test_uncertainty
    )

    # Calculate calibrated coverage
    coverage_80_calibrated = np.mean(
        (calibrated_forecast['y'] >= calibrated_forecast['yhat_lower_80_calibrated']) &
        (calibrated_forecast['y'] <= calibrated_forecast['yhat_upper_80_calibrated'])
    )

    coverage_95_calibrated = np.mean(
        (calibrated_forecast['y'] >= calibrated_forecast['yhat_lower_95_calibrated']) &
        (calibrated_forecast['y'] <= calibrated_forecast['yhat_upper_95_calibrated'])
    )

    print(f"\nCalibration Results:")
    print(f"  - Calibrated 80% Interval Coverage: {coverage_80_calibrated*100:.2f}% (Target: 80%)")
    print(f"  - Calibrated 95% Interval Coverage: {coverage_95_calibrated*100:.2f}% (Target: 95%)")

    # Calculate improvement
    improvement_80 = abs(coverage_80_calibrated - 0.80) * 100
    improvement_95 = abs(coverage_95_calibrated - 0.95) * 100

    print(f"\nCalibration Improvement:")
    print(f"  - 80% Interval Error after calibration: {improvement_80:.2f}%")
    print(f"  - 95% Interval Error after calibration: {improvement_95:.2f}%")

    calibration_info = {
        'coverage_80_calibrated': coverage_80_calibrated,
        'coverage_95_calibrated': coverage_95_calibrated,
        'calibrated_z_80': calibrated_z_80,
        'calibrated_z_95': calibrated_z_95,
        'improvement_80': improvement_80,
        'improvement_95': improvement_95
    }

    return calibrated_forecast, calibration_info

# Calibrate model if needed
if metrics['needs_calibration']:
    calibrated_forecast, calibration_info = calibrate_prediction_intervals(
        model, forecast, train_df, test_forecast
    )
else:
    print("\nSkipping calibration - model is already well calibrated.")
    calibrated_forecast = test_forecast.copy()
    calibration_info = {
        'coverage_80_calibrated': metrics['coverage_80_initial'],
        'coverage_95_calibrated': metrics['coverage_95_initial'],
        'calibrated_z_80': 1.28,
        'calibrated_z_95': 1.96,
        'improvement_80': 0,
        'improvement_95': 0
    }

# Visualize forecasting results
def visualize_results(train_df, test_df, forecast, calibrated_forecast, metrics, calibration_info):
    """
    Create comprehensive visualizations of forecasting results.

    Parameters:
    train_df: Training data
    test_df: Test data
    forecast: Forecast results
    calibrated_forecast: Calibrated forecast
    metrics: Evaluation metrics
    calibration_info: Calibration information
    """

    fig = plt.figure(figsize=(18, 12))

    # 1. Full forecast with intervals
    ax1 = plt.subplot(3, 2, 1)
    ax1.plot(train_df['ds'], train_df['y'], 'b-', alpha=0.7, label='Training Data')
    ax1.plot(test_df['ds'], test_df['y'], 'g-', alpha=0.7, label='Actual Test Data')
    ax1.plot(forecast['ds'], forecast['yhat'], 'r--', alpha=0.9, label='Forecast')

    # Plot 95% prediction intervals
    ax1.fill_between(
        forecast['ds'],
        forecast['yhat_lower'],
        forecast['yhat_upper'],
        alpha=0.2, color='red', label='95% Prediction Interval'
    )

    ax1.set_title('Full Time Series Forecast with 95% Prediction Intervals')
    ax1.set_xlabel('Date')
    ax1.set_ylabel('Value')
    ax1.legend(loc='upper left')
    ax1.grid(True, alpha=0.3)

    # 2. Test period zoom with calibrated intervals
    ax2 = plt.subplot(3, 2, 2)
    test_dates = calibrated_forecast['ds']

    ax2.plot(test_dates, calibrated_forecast['y'], 'g-', alpha=0.9, label='Actual', linewidth=2)
    ax2.plot(test_dates, calibrated_forecast['yhat'], 'r--', alpha=0.9, label='Forecast', linewidth=2)

    # Plot calibrated intervals if available
    if 'yhat_lower_95_calibrated' in calibrated_forecast.columns:
        ax2.fill_between(
            test_dates,
            calibrated_forecast['yhat_lower_95_calibrated'],
            calibrated_forecast['yhat_upper_95_calibrated'],
            alpha=0.2, color='orange', label='Calibrated 95% Interval'
        )
    else:
        ax2.fill_between(
            test_dates,
            calibrated_forecast['yhat_lower'],
            calibrated_forecast['yhat_upper'],
            alpha=0.2, color='red', label='95% Interval'
        )

    ax2.set_title('Test Period: Actual vs Forecast with Intervals')
    ax2.set_xlabel('Date')
    ax2.set_ylabel('Value')
    ax2.legend(loc='upper left')
    ax2.grid(True, alpha=0.3)

    # 3. Coverage comparison
    ax3 = plt.subplot(3, 2, 3)
    coverages = ['80%', '95%']
    initial_coverages = [metrics['coverage_80_initial']*100, metrics['coverage_95_initial']*100]
    calibrated_coverages = [calibration_info['coverage_80_calibrated']*100,
                           calibration_info['coverage_95_calibrated']*100]
    target_coverages = [80, 95]

    x = np.arange(len(coverages))
    width = 0.25

    ax3.bar(x - width, initial_coverages, width, label='Initial', color='skyblue')
    ax3.bar(x, calibrated_coverages, width, label='Calibrated', color='lightgreen')
    ax3.bar(x + width, target_coverages, width, label='Target', color='orange', alpha=0.6)

    ax3.set_xlabel('Prediction Interval')
    ax3.set_ylabel('Empirical Coverage (%)')
    ax3.set_title('Coverage Rates: Initial vs Calibrated vs Target')
    ax3.set_xticks(x)
    ax3.set_xticklabels(coverages)
    ax3.legend()
    ax3.grid(True, alpha=0.3)

    # Add value labels
    for i, (init, cal) in enumerate(zip(initial_coverages, calibrated_coverages)):
        ax3.text(i - width, init + 1, f'{init:.1f}%', ha='center', va='bottom', fontsize=9)
        ax3.text(i, cal + 1, f'{cal:.1f}%', ha='center', va='bottom', fontsize=9)

    # 4. Residual analysis
    ax4 = plt.subplot(3, 2, 4)
    residuals = calibrated_forecast['y'] - calibrated_forecast['yhat']
    ax4.scatter(calibrated_forecast['yhat'], residuals, alpha=0.6, color='purple')
    ax4.axhline